AWSTemplateFormatVersion: "2010-09-09"
Description: The settings for s3strm

Parameters:
  SettingsBucket:
    Type: String
    Description: The name of the settings bucket to be created

  MoviesBucket:
    Type: String
    Description: The bucket where your movies are kept

  OMDbAPIKey:
    Type: String
    Description: Your peronsal OMDb API key

  APIGatewayURL:
    Type: String
    Description: The endpoint of the API Gateway

Resources:
  GeneralBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
      BucketName: !Ref SettingsBucket

Outputs:
  SettingsBucket:
    Description: A bucket where s3strm can store settings
    Value:
      !Ref SettingsBucket
    Export:
      Name: s3strm-settings-bucket

  MoviesBucket:
    Description: A bucket where movies can be found
    Value:
      !Ref MoviesBucket
    Export:
      Name: s3strm-movies-bucket

  OMDbAPIKey:
    Description: Your personal OMDb API key
    Value:
      !Ref OMDbAPIKey
    Export:
      Name: s3strm-omdb-api-key

  APIGatewayURL:
    Description: The public URL of the s3strm API
    Value:
      !Ref APIGatewayURL
    Export:
      Name: s3strm-api-gateway-url
