AWSTemplateFormatVersion: "2010-09-09"
Description: The settings for s3strm

Parameters:
  SettingsBucket:
    Type: String
    Description: The name of the settings bucket to be created

  MoviesBucket:
    Type: String
    Description: The bucket where your movies are kept

  OMDbAPIKey:
    Type: String
    Description: Your peronsal OMDb API key

  APIKey:
    Type: String
    Description: Global API Key

  APIGatewayDomain:
    Type: String
    Description: Production API Gateway stage

  APIGatewayDomainHostedZoneId:
    Type: String
    Default: prod
    Description: Route53 Hosted Zone ID for the Production API Gateway domain

  APIGatewayStage:
    Type: String
    Default: prod
    Description: Production API Gateway stage

Resources:
  GeneralBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
      BucketName: !Ref SettingsBucket

Outputs:
  SettingsBucket:
    Description: A bucket where s3strm can store settings
    Value:
      !Ref SettingsBucket
    Export:
      Name: s3strm-settings-bucket

  MoviesBucket:
    Description: A bucket where movies can be found
    Value:
      !Ref MoviesBucket
    Export:
      Name: s3strm-movies-bucket

  OMDbAPIKey:
    Description: Your personal OMDb API key
    Value:
      !Ref OMDbAPIKey
    Export:
      Name: s3strm-omdb-api-key

  APIGatewayDomain:
    Description: The domain name to apply to the API Gateway
    Value:
      !Ref APIGatewayDomain
    Export:
      Name: s3strm-api-gateway-domain

  APIGatewayDomainHostedZoneId:
    Description: The domain name to apply to the API Gateway
    Value:
      !Ref APIGatewayDomainHostedZoneId
    Export:
      Name: s3strm-api-gateway-domain-hosted-zone-id

  APIKey:
    Description: The global API Key
    Value:
      !Ref APIKey
    Export:
      Name: s3strm-api-key
